version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - intrange
    - ireturn
    - nonamedreturns
    - varnamelen
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      enabled-tags:
        - performance
        - opinionated
        - diagnostic
        - style
    cyclop:
      max-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - cyclop
          - revive
        path: ._test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
